/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.alanjin.smsmms.frontend;

import java.awt.CardLayout;
import java.awt.Font;
import java.awt.LayoutManager;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Date;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableModel;
import org.alanjin.smsmms.backend.bean.Member;
import org.alanjin.smsmms.backend.dao.MemberDao;
import org.alanjin.smsmms.backend.dao.MemberDaoImpl;
import org.alanjin.smsmms.backend.service.MemberAction;

/**
 *
 * @author Administrator
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        setUIFont();
        setUI();
        initComponents();
    }
    
    /**
    * 设置字体，使用系统默认，12px
    */
   public void setUIFont() {
            FontUIResource f=new FontUIResource("default", Font.PLAIN,12);
            java.util.Enumeration<Object> keys = UIManager.getDefaults().keys();
            while (keys.hasMoreElements()) {
                    Object key = keys.nextElement();
                    Object value = UIManager.get(key);
                    if (value instanceof javax.swing.plaf.FontUIResource)
                            UIManager.put(key, f);
            }
   }

    /**
     * 设置UIManager
     */
    public void setUI(){
            //设置UIMangager为系统默认
            try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            } catch (Exception e) {
                    e.printStackTrace();
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DeleteDialog = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        indexPanel = new javax.swing.JPanel();
        welcomePanel = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        memberPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        memberTable = new javax.swing.JTable();
        buttonPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        filterPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Date initDate = new Date(0);
        datePicker1 = new com.eltima.components.ui.DatePicker(initDate, BirthDayFormat, datePickerFont, null);
        jButton9 = new javax.swing.JButton();
        addMemberPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        p2pPanel = new javax.swing.JPanel();
        messPanel = new javax.swing.JPanel();
        viewReplyPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        homeMenu = new javax.swing.JMenu();
        showHomeMenu = new javax.swing.JMenuItem();
        MemberMenu = new javax.swing.JMenu();
        ListAllMenuItem = new javax.swing.JMenuItem();
        AddNewMenuItem = new javax.swing.JMenuItem();
        SMSMenu = new javax.swing.JMenu();
        P2PMenuItem = new javax.swing.JMenuItem();
        MessMenuItem = new javax.swing.JMenuItem();
        ViewReplyMenuItem = new javax.swing.JMenuItem();
        MsgModelMenuItem = new javax.swing.JMenuItem();
        TimerMenuItem = new javax.swing.JMenuItem();
        AdminMenu = new javax.swing.JMenu();
        PasswdMenuItem = new javax.swing.JMenuItem();
        AdminMenuItem = new javax.swing.JMenuItem();
        HistoryMenuItem = new javax.swing.JMenuItem();
        SyncMenuItem = new javax.swing.JMenuItem();
        AboutMenu = new javax.swing.JMenu();
        AboutAppMenuItem = new javax.swing.JMenuItem();

        DeleteDialog.setTitle("删除勾选的会员");
        DeleteDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DeleteDialog.setResizable(false);

        javax.swing.GroupLayout DeleteDialogLayout = new javax.swing.GroupLayout(DeleteDialog.getContentPane());
        DeleteDialog.getContentPane().setLayout(DeleteDialogLayout);
        DeleteDialogLayout.setHorizontalGroup(
            DeleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        DeleteDialogLayout.setVerticalGroup(
            DeleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jButton1.setText("全选");

        jButton2.setText("删除");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("修改会费");

        jButton4.setText("修改基本资料");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(0, 565, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton4});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("史山寺佛恩互助会会员管理系统");
        setPreferredSize(new java.awt.Dimension(804, 650));
        setResizable(false);

        indexPanel.setMinimumSize(new java.awt.Dimension(780, 560));
        indexPanel.setLayout(new java.awt.CardLayout());

        welcomePanel.setMinimumSize(new java.awt.Dimension(780, 560));
        welcomePanel.setPreferredSize(new java.awt.Dimension(800, 600));

        jTextField1.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        jTextField1.setText("Hello World!");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout welcomePanelLayout = new javax.swing.GroupLayout(welcomePanel);
        welcomePanel.setLayout(welcomePanelLayout);
        welcomePanelLayout.setHorizontalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePanelLayout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
        );
        welcomePanelLayout.setVerticalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePanelLayout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(240, Short.MAX_VALUE))
        );

        indexPanel.add(welcomePanel, "card7");

        memberPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        memberPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        memberPanel.setLayout(new java.awt.BorderLayout());

        memberTable.setModel(new DefaultTableModel(
            new String [] {
                "select", "姓名", "性别", "手机号", "出生日期", "入会日期", "累计会费"
            },0) {
                Class[] types = new Class [] {
                    java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
                };
                @Override
                public Class getColumnClass(int c)	{
                    Object value = getValueAt(0, c);
                    if(value!=null)
                    return value.getClass();
                    else return super.getClass();
                }
            });
            memberTable.getColumn("select").setHeaderRenderer(check);
            memberTable.getTableHeader().addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e){
                    if(memberTable.getColumnModel().getColumnIndexAtX(e.getX())==0){//如果点击的是第0列，即checkbox这一列
                        JCheckBox Checkbox = (JCheckBox)check;
                        boolean b = !check.isSelected();
                        check.setSelected(b);
                        memberTable.getTableHeader().repaint();
                        for(int i=0;i<memberTable.getRowCount();i++){
                            memberTable.getModel().setValueAt(b, i, 0);//把这一列都设成和表头一样
                        }
                    }
                }
            });
            jScrollPane2.setViewportView(memberTable);

            memberPanel.add(jScrollPane2, java.awt.BorderLayout.CENTER);

            buttonPanel1.setMinimumSize(new java.awt.Dimension(800, 33));

            jButton5.setText("jButton5");
            buttonPanel1.add(jButton5);

            jButton6.setText("jButton6");
            buttonPanel1.add(jButton6);

            jButton7.setText("jButton7");
            buttonPanel1.add(jButton7);

            jButton8.setText("jButton8");
            buttonPanel1.add(jButton8);

            memberPanel.add(buttonPanel1, java.awt.BorderLayout.PAGE_END);

            jLabel1.setText("选择出生日期：");

            jButton9.setText("筛选");

            javax.swing.GroupLayout filterPanelLayout = new javax.swing.GroupLayout(filterPanel);
            filterPanel.setLayout(filterPanelLayout);
            filterPanelLayout.setHorizontalGroup(
                filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(filterPanelLayout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(jLabel1)
                    .addGap(18, 18, 18)
                    .addComponent(datePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(52, 52, 52)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            filterPanelLayout.setVerticalGroup(
                filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filterPanelLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton9)
                        .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(datePicker1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addContainerGap())
            );

            memberPanel.add(filterPanel, java.awt.BorderLayout.PAGE_START);

            indexPanel.add(memberPanel, "card2");

            addMemberPanel.setPreferredSize(new java.awt.Dimension(800, 600));

            jLabel3.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
            jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel3.setText("会员删除/修改");

            javax.swing.GroupLayout addMemberPanelLayout = new javax.swing.GroupLayout(addMemberPanel);
            addMemberPanel.setLayout(addMemberPanelLayout);
            addMemberPanelLayout.setHorizontalGroup(
                addMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1)
            );
            addMemberPanelLayout.setVerticalGroup(
                addMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(addMemberPanelLayout.createSequentialGroup()
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
            );

            indexPanel.add(addMemberPanel, "card3");

            p2pPanel.setPreferredSize(new java.awt.Dimension(800, 600));

            javax.swing.GroupLayout p2pPanelLayout = new javax.swing.GroupLayout(p2pPanel);
            p2pPanel.setLayout(p2pPanelLayout);
            p2pPanelLayout.setHorizontalGroup(
                p2pPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 10, Short.MAX_VALUE)
            );
            p2pPanelLayout.setVerticalGroup(
                p2pPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 10, Short.MAX_VALUE)
            );

            indexPanel.add(p2pPanel, "card4");

            messPanel.setPreferredSize(new java.awt.Dimension(800, 600));

            javax.swing.GroupLayout messPanelLayout = new javax.swing.GroupLayout(messPanel);
            messPanel.setLayout(messPanelLayout);
            messPanelLayout.setHorizontalGroup(
                messPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 10, Short.MAX_VALUE)
            );
            messPanelLayout.setVerticalGroup(
                messPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 10, Short.MAX_VALUE)
            );

            indexPanel.add(messPanel, "card5");

            viewReplyPanel.setPreferredSize(new java.awt.Dimension(800, 600));

            javax.swing.GroupLayout viewReplyPanelLayout = new javax.swing.GroupLayout(viewReplyPanel);
            viewReplyPanel.setLayout(viewReplyPanelLayout);
            viewReplyPanelLayout.setHorizontalGroup(
                viewReplyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 10, Short.MAX_VALUE)
            );
            viewReplyPanelLayout.setVerticalGroup(
                viewReplyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 10, Short.MAX_VALUE)
            );

            indexPanel.add(viewReplyPanel, "card6");

            jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

            homeMenu.setText("首页");

            showHomeMenu.setText("显示首页");
            showHomeMenu.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseReleased(java.awt.event.MouseEvent evt) {
                    showHomeMenuMouseReleased(evt);
                }
            });
            showHomeMenu.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    showHomeMenuActionPerformed(evt);
                }
            });
            homeMenu.add(showHomeMenu);

            jMenuBar1.add(homeMenu);

            MemberMenu.setText("会员管理");

            ListAllMenuItem.setText("查看全部");
            ListAllMenuItem.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    ListAllMenuItemActionPerformed(evt);
                }
            });
            MemberMenu.add(ListAllMenuItem);

            AddNewMenuItem.setText("添加新会员");
            AddNewMenuItem.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    AddNewMenuItemActionPerformed(evt);
                }
            });
            MemberMenu.add(AddNewMenuItem);

            jMenuBar1.add(MemberMenu);

            SMSMenu.setText("短信管理");

            P2PMenuItem.setText("点对点短信");
            P2PMenuItem.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    P2PMenuItemActionPerformed(evt);
                }
            });
            SMSMenu.add(P2PMenuItem);

            MessMenuItem.setText("短信群发");
            SMSMenu.add(MessMenuItem);

            ViewReplyMenuItem.setText("查看回复");
            SMSMenu.add(ViewReplyMenuItem);

            MsgModelMenuItem.setText("短信模版");
            SMSMenu.add(MsgModelMenuItem);

            TimerMenuItem.setText("定时发送");
            SMSMenu.add(TimerMenuItem);

            jMenuBar1.add(SMSMenu);

            AdminMenu.setText("管理员");

            PasswdMenuItem.setText("修改密码");
            AdminMenu.add(PasswdMenuItem);

            AdminMenuItem.setText("登陆管理");
            AdminMenu.add(AdminMenuItem);

            HistoryMenuItem.setText("操作记录");
            AdminMenu.add(HistoryMenuItem);

            SyncMenuItem.setText("数据同步");
            AdminMenu.add(SyncMenuItem);

            jMenuBar1.add(AdminMenu);

            AboutMenu.setText("关于");

            AboutAppMenuItem.setText("关于本软件");
            AboutMenu.add(AboutAppMenuItem);

            jMenuBar1.add(AboutMenu);

            setJMenuBar(jMenuBar1);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 864, Short.MAX_VALUE)
                    .addComponent(indexPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 865, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 535, Short.MAX_VALUE)
                    .addComponent(indexPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 534, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void P2PMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P2PMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P2PMenuItemActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO 获得所选择的memberId list， 并拿到个数
        if(JOptionPane.showConfirmDialog(null, "确定删除所选则的N个会员？", "删除会员", JOptionPane.OK_CANCEL_OPTION) == 0)
            // TODO 删除所选会员信息
            ;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ListAllMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListAllMenuItemActionPerformed
        // TODO add your handling code here:
        //if(JOptionPane.showConfirmDialog(null, "确定删除所选则的N个会员？", "删除会员", JOptionPane.OK_CANCEL_OPTION) == 0)
        
        List<Member> allMembers = memberAction.getAllMembers();
        Util.fillMemberTable(memberTable, allMembers);
        
        LayoutManager layout = this.indexPanel.getLayout();
        if(layout instanceof CardLayout) {
            CardLayout card = (CardLayout) layout;
            card.show(indexPanel, "card2");
        }
    }//GEN-LAST:event_ListAllMenuItemActionPerformed

    private void AddNewMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewMenuItemActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = this.indexPanel.getLayout();
        if(layout instanceof CardLayout) {
            CardLayout card = (CardLayout) layout;
            card.show(indexPanel, "card3");
        }
    }//GEN-LAST:event_AddNewMenuItemActionPerformed

    private void showHomeMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showHomeMenuMouseReleased
        LayoutManager layout = this.indexPanel.getLayout();
        if(layout instanceof CardLayout) {
            CardLayout card = (CardLayout) layout;
            card.first(indexPanel);
        }
    }//GEN-LAST:event_showHomeMenuMouseReleased

    private void showHomeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showHomeMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showHomeMenuActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    MemberAction memberAction = MemberAction.newInstance();
    private static final String DefaultFormat = "yyyy-MM-dd hh:mm:ss";
    private static final String BirthDayFormat = "yyyy-MM-dd";
    private static final Font datePickerFont=new Font("Times New Roman", Font.PLAIN, 14);
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutAppMenuItem;
    private javax.swing.JMenu AboutMenu;
    private javax.swing.JMenuItem AddNewMenuItem;
    private javax.swing.JMenu AdminMenu;
    private javax.swing.JMenuItem AdminMenuItem;
    private javax.swing.JDialog DeleteDialog;
    private javax.swing.JMenuItem HistoryMenuItem;
    private javax.swing.JMenuItem ListAllMenuItem;
    private javax.swing.JMenu MemberMenu;
    private javax.swing.JMenuItem MessMenuItem;
    private javax.swing.JMenuItem MsgModelMenuItem;
    private javax.swing.JMenuItem P2PMenuItem;
    private javax.swing.JMenuItem PasswdMenuItem;
    private javax.swing.JMenu SMSMenu;
    private javax.swing.JMenuItem SyncMenuItem;
    private javax.swing.JMenuItem TimerMenuItem;
    private javax.swing.JMenuItem ViewReplyMenuItem;
    private javax.swing.JPanel addMemberPanel;
    private javax.swing.JPanel buttonPanel1;
    private com.eltima.components.ui.DatePicker datePicker1;
    private javax.swing.JPanel filterPanel;
    private javax.swing.JMenu homeMenu;
    private javax.swing.JPanel indexPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel memberPanel;
    private javax.swing.JTable memberTable;
    final CheckBoxRenderer check = new CheckBoxRenderer();
    private javax.swing.JPanel messPanel;
    private javax.swing.JPanel p2pPanel;
    private javax.swing.JMenuItem showHomeMenu;
    private javax.swing.JPanel viewReplyPanel;
    private javax.swing.JPanel welcomePanel;
    // End of variables declaration//GEN-END:variables
}
